name: Sync main branch
on:
  push:
    branches:
      - 'main'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge main -> php82
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: php82
          github_token: ${{ github.token }}
